### ISSUE TITLE
Version 4.4.0 is incompatible with Spree Backend 4.4.1

### ISSUE THREAD

**Issue by albertoalmagro** [spree/spree_legacy_frontend#17]
The version 4.4.0 of this gem is incompatible with Spree Backend 4.4.1 due to javascript issues.

## Context
After following all the steps to upgrade Spree to 4.4.0 following the [upgrade guide](https://dev-docs.spreecommerce.org/upgrades/upgrades/4.3-to-4.4#add-activejob-queues), during the smoke test phase I realized that the javascript from Spree Legacy Frontend had stopped working.

I think this issue is caused because both Spree Legacy Frontend and Spree Backend define `Spree.ready` in their respective `spree.js` files in a conflictive way:
- Spree Legacy Frontend: https://github.com/spree/spree_legacy_frontend/blob/v4.4.0/app/assets/javascripts/spree.js#L5
- Spree Backend: https://github.com/spree/spree_backend/blob/v4.4.1/app/assets/javascripts/spree.js#L5

Spree Legacy Frontend v4.4.0 defines `Spree.ready` adding listeners to `page:load` and `turbolinks:load` events (`turbo:load` in `main` branch), while Spree Backend defines `Spree.ready` adding a listeners to `spree:load` event. Since both functions have the same name and Spree Backend is loaded after Spree Legacy Frontend, `Spree.ready` gets overwritten in a way that just listens to `spree:load`, but Spree Legacy Frontend does not know how to handle that.

## Expected Behavior
Spree 4.4.x, Spree Legacy Frontend 4.4.x and Spree Backend 4.4.x are compatible.

## Possible Fix
Two possible solutions come to my mind:
- I have started exploring renaming the `Spree` object in Spree Legacy Frontend javascript files as `SpreeFrontend`. But so far it raises a `NameError` at `lib/spree/frontend/configuration.rb:3:in ` telling `<module:Frontend>: uninitialized constant Spree::Preferences`.
- Reworking Spree Legacy Frontend javascript files so that `Spree.ready` listener also listens to `spree:load`, although that would imply maintaining a dependency between Spree Legacy Frontend and Spree Backend, which probably makes this less desirable long term.

**Comment by rafalcymerys** [comment]
@albertoalmagro thank you for reporting this!

It seems like the main issue is that both files are named spree.js in their respective rails engines. This causes them to override each other during asset pipeline compilation.
Wouldn't a solution be to rename e.g. spree.js in spree_legacy_frontend to e.g. `spree_frontend.js` and then update `app/assets/javascripts/spree/frontend.js:7` to `//= require spree_frontend` ?
