### ISSUE TITLE
Could not render layout: layout preference not defined

### ISSUE THREAD

**Issue by pCosta99** [spree/spree_legacy_frontend#2]
## Context

I was trying to simply setup spree frontend with the new headless spree and expected it to be a frictionless process.

## Expected Behavior
After copying spree-starter-main and introducing this gem I expected to have a non-buggy shop.

## Actual Behavior
It  has the bug mentioned in the title.

## Possible Fix
So, according to my research, this should only be a matter of a missing preference. I tried following all suggestions mentioned on this [SF post](https://stackoverflow.com/questions/21840963/change-spree-application-layout-file-to-load) but none of them seemed to work.

So, after some extra looking into the source code, my proposed change is to add the preference as a default value on ``app/models/spree/frontend_configuration.rb``. I opened a PR with the proposed change.

## Steps to Reproduce

1. Download spree_starter-main.zip from https://github.com/spree/spree_starter/archive/main.zip
2. Cd into the directory and add ``gem 'spree_frontend'`` to Gemfile
3. Run ``rails g spree:frontend:install``
4. Run ``bin/setup``

Ideally for me this should provide a non breaking access to localhost:4000.

## Your Environment
* Version used: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
* Gemfile and Gemfile.lock as text in a Gist:
  * Gemfile -> https://gist.github.com/pCosta99/948f43b618840b0c40bff468e32cde7e
  * Gemfile.lock -> https://gist.github.com/pCosta99/7babf978a776bd8b8b1e3ab963b57335
* Any relevant stack traces ("Full trace" preferred):
https://gist.github.com/pCosta99/595f3549947bcadaa2d86b5740579816 (full)

**Comment by pCosta99** [comment]
I pulled the code to the change I wanted and I realized it's already correct in here. My problem then becomes the gem being "outdated" (?). Since that no longer represents an issue with this repository, I'm closing the issue!

**Comment by fuzzkat** [comment]
@pCosta99 did you work out what version is working?  I'm still experiencing this issue with the latest releases from `bundle update` today.  Mostly spree_*: 4.4.0.

**Comment by pCosta99** [comment]
@fuzzkat my approach was to use this repository instead of a specific version. Never managed to get it working with a specific version without having to make changes (which I can't recall).
Here's what I'm using atm:
```
gem 'spree_frontend', github: 'spree/spree_legacy_frontend'
```

The repository doesn't receive any updates except for bug fixes so it doesn't seems too bad to aim it here.

**Comment by fuzzkat** [comment]
Fantastic, thanks @pCosta99! - I should have thought of that.  Would be nice if someone on this project could update the Gem with the current version, since the one currently hosted at rubygems.org doesn't work with the latest Spree core.

**Comment by pCosta99** [comment]
No problem! I had the issue open for some days before closing it up, maybe there isn't a lot of attention on this branch right now... But that would be nice for sure
